config/routes.rb
Rails.application.routes.draw do

  scope module: 'shared' do
    resources :account_activations, only: [:edit]
    resources :password_resets, only: [:new, :create, :edit, :update]
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
    get '/signup', to: 'users#new'
    post '/signup', to: 'users#create'
  end

  namespace :admin do
    root 'pages#index'
    resources :users, except: :new
    resources :countries
    resources :leagues do
      resources :seasons do
        resources :matches, only: :index
      end
      resources :matches
    end
    resources :seasons, only: [:index, :new]
    resources :matches, only: [:index, :new]
    resources :clubs
  end

  scope module: 'site' do
    root 'matches#index'
    get '/search',   to: 'matches#search'
    get '/contacts', to: 'pages#contacts'
    get '/about',    to: 'pages#about'
    get '/:league_slug',              to: 'leagues#matches', as: 'league_matches'
    get '/:league_slug/:season_slug', to: 'seasons#matches', as: 'season_matches',
        season_slug: /\d{4}-\d{4}/
    get '/:league_slug/:season_slug/:club_slug', to: 'clubs#matches',
        as: 'club_matches', season_slug: /\d{4}-\d{4}/
    get '/:league_slug/:match_slug',  to: 'matches#show',  as: 'match'

  end

end

app/models/match.rb
class Match < ActiveRecord::Base
  searchkick language: 'Russian', word_start: [:search], word_end: [:search]
  belongs_to :home, class_name: 'Club', required: true
  belongs_to :away, class_name: 'Club', required: true
  belongs_to :season, required: true, validate: true, counter_cache: true

  before_validation :generate_title
  before_save :generate_search

  extend FriendlyId
  friendly_id :title, use: [:slugged, :history]

  validates :home_score, numericality: { only_integer: true,
                                         greater_than_or_equal_to: 0,
                                         less_than: 200},
            presence: true
  validates :away_score, numericality: { only_integer: true,
                                         greater_than_or_equal_to: -1,
                                         less_than: 200},
            presence: true
  validates_presence_of :play_date, :home_id, :away_id, :video, :season_id,
                        :user_id, :slug
  validate :home_and_away_cannot_be_same
  validate :home_and_away_penalties_cannot_be_same
  validate :penalties_must_present_both
  validate :if_penalties_present_result_must_be_equal

  def home_and_away_cannot_be_same
    if home_id.present? && away_id.present?
      if home_id == away_id
        errors.add(:home_id, 'не может совпадать с клубом гостем')
      end
    end
  end

  def home_and_away_penalties_cannot_be_same
    if home_penalty.present? && away_penalty.present?
      if home_penalty == away_penalty
        errors.add(:home_penalty, 'не может быть одинаковым с пенальти гостей')
      end
    end
  end

  def penalties_must_present_both
    if (home_penalty.present? || away_penalty.present?) &&
       !(home_penalty.present? && away_penalty.present?)
      if (home_penalty.present?)
        errors.add(:away_penalty, 'должно быть указано')
      else
        errors.add(:home_penalty, 'должно быть указано')
      end
    end
  end

  def if_penalties_present_result_must_be_equal
    if home_penalty.present? && away_penalty.present?
      if home_score != away_score
        errors.add(:home_score, 'должен быть одинаковым с голами гостей
                                 если указаны послематчевые пенальти')
      end
    end
  end

  def penalties?
    home_penalty.present?
  end

  def match_title()
    if penalties?
      "#{home.name} (#{home.city}) - #{away.name} (#{away.city}) " +
      "#{home_score}:#{away_score} " +
      "(#{home_penalty}:#{away_penalty}) - " + play_date.strftime('%d.%m.%Y')
    else
      "#{home.name} (#{home.city}) - #{away.name} (#{away.city}) " +
      "#{home_score}:#{away_score} - " + play_date.strftime('%d.%m.%Y')
    end
  end

  def match_search()
    match_title + " #{season.league.name} - #{season.name}"
  end

  def normalize_friendly_id(string)
    string += ' обзор матча'
    string = string.mb_chars.downcase.to_s
    I18n.transliterate(string.gsub(/:/, '-').gsub(/[()]/, '')).parameterize
  end

  def search_data
    {
      search: search,
      play_date: play_date
    }
  end

  def should_generate_new_friendly_id?
    title_changed?
  end

  private

    def generate_title
      self.title = match_title
    end

    def generate_search
      self.search = match_search
    end
end

app/controllers/admin/matches_controller.rb
class Admin::MatchesController < AdminBaseController
  before_action :set_roles
  before_action :require_authorization

  def index
    if (request.original_url == admin_matches_url)
      @countries = Country.where('leagues_count > 0').includes(leagues: :seasons).
                          where('leagues.seasons_count > 0').references(:leagues).
                          where('seasons.matches_count > 0').references(:seasons)
      path = :admin_league_season_matches_path
      render 'list', locals: { path: path }
    else
      @matches = Match.where('season_id = ?', params[:season_id]).
                      paginate(page: params[:page], per_page: 10).order(created_at: :desc)
      render 'index'
    end
  end

  def new
    @match = Match.new
    if (request.original_url == new_admin_match_url)
      @countries = Country.where('leagues_count > 0').includes(leagues: :seasons)
                          .where('leagues.seasons_count > 0').references(:seasons)
      path = :new_admin_league_match_path
      render 'list', locals: { path: path }
    else
      @league = League.find(params['league_id'])
      @clubs = Club.where('country_id = ?', @league.country_id).order(name: :asc)
      @seasons = Season.where('league_id = ?', @league.id).order(end_on: :desc)
      render 'new'
    end
  end

  def create
    @match = current_user.matches.new(match_params)
    if @match.save
      flash[:success] = 'Матч добавлен'
      redirect_to(admin_league_match_path(@match.season.league.id, @match.id))
    else
      @league = League.find(params['league_id'])
      render 'new'
    end
  end

  def show
    @match = Match.find(params[:id])
  end

  def edit
    @league = League.find(params['league_id'])
    @match = Match.find(params[:id])
    @clubs = Club.where('country_id = ?', @league.country_id).order(name: :asc)
    @seasons = Season.where('league_id = ?', @league.id).order(end_on: :desc)
  end

  def update
    @match = Match.find(params[:id])
    if @match.update(match_params)
      flash[:success] = 'Матч отредактирован'
      redirect_to(admin_league_match_path(@match.season.league.id, @match.id))
    else
      @league = League.find(params['league_id'])
      render 'edit'
    end
  end

  def destroy
    @match = Match.find(params[:id])
    @match.destroy
    flash[:success] = 'Матч удален'
    redirect_to request.referrer || admin_root_url
  end

  private

    def set_roles
      @roles = %w(journalist moderator admin)
    end

    # Use strong_parameters for attribute whitelisting
    # Be sure to update your create() and update() controller methods.
    def match_params
      params.require(:match).permit(:play_date, :home_id, :away_id, :home_score,
                                    :away_score, :video, :season_id, :user_id,
                                    :home_penalty, :away_penalty)
    end
end

app/controllers/site/matches_controller.rb
class Site::MatchesController < ApplicationController

  def index
    @matches = Match.paginate(page: params[:page], per_page: 10).
                    order(created_at: :desc)
    @last_seasons = Season.select('DISTINCT ON (league_id) *').
                          order(:league_id, end_on: :desc)
  end

  def show
    @match = Match.friendly.find(params[:match_slug])
    if request.path != match_path(@match.season.league.slug, @match)
      redirect_to match_path(@match.season.league.slug, @match),
                  status: :moved_permanently
    end
  end

  def search
    @search_results = Match.search(params[:q], fields: [{search: :word_start},
                                                        {search: :word_end}],
                                   order: {play_date: :desc}, limit: 6)
  end
end

app/helpers/admin/matches_helper.rb
module Admin::MatchesHelper
end

app/helpers/site/matches_helper.rb
module Site::MatchesHelper
  def home_outcome(match)
    if match.home_score > match.away_score
      :winner
    elsif match.home_score < match.away_score
      :loser
    else
      if match.penalties?
        if match.home_penalty > match.away_penalty
          :winner
        else
          :loser
        end
      end
    end
  end

  def away_outcome(match)
    if match.away_score > match.home_score
      :winner
    elsif match.away_score < match.home_score
      :loser
    else
      if match.penalties?
        if match.away_penalty > match.home_penalty
          :winner
        else
          :loser
        end
      end
    end
  end
end

app/views/admin/matches/edit.html.haml
- provide(:title, 'Редактирование клуба')

.row
  .col-md-6.col-md-offset-3
    %h1.text-center Редактирование матча

    = form_for(@match, url: admin_league_match_path(@league.id, @match.id)) do |f|
      = render 'shared/error_messages', object: @match

      .form-group
        = f.label :started_on, 'Дата'
        .form-inline
          = f.date_select :play_date, { use_two_digit_numbers: true }, class: 'form-control'

      .form-group
        = f.label :home_id, 'Клуб хозяин'
        = f.collection_select(:home_id, @clubs, :id, :name, {}, class: 'form-control' )

      .form-group
        = f.label :away_id, 'Клуб гость'
        = f.collection_select(:away_id, @clubs, :id, :name, {}, class: 'form-control')

      .form-inline
        = f.text_field :home_score, class: 'form-control', placeholder: 'Голы хозяина'
        %span.colon :
        = f.text_field :away_score, class: 'form-control', placeholder: 'Голы гостей'

      .form-inline
        = f.text_field :home_penalty, class: 'form-control', placeholder: 'Пенальти хозяев'
        %span.colon :
        = f.text_field :away_penalty, class: 'form-control', placeholder: 'Пенальти гостей'
        %p.help-block
          Если отсутсвовали послематчевые пенальти поля оставлять пустыми

      .form-group
        = f.text_area :video, class: 'form-control', placeholder: 'Видео'

      .form-group
        = f.label :season_id, 'Сезон'
        = f.collection_select(:season_id, @seasons, :id, :name, {}, class: 'form-control' )

      = f.submit 'Редактировать', class: 'btn btn-lg btn-primary btn-block'

app/views/admin/matches/index.html.haml
- provide(:title, 'Список матчей по сезонам')

%ul.list-group
- @matches.each do |match|
  %li.list-group-item
    = link_to match.title,
              admin_league_match_path(match.season.league.id, match.id)
    .actions.pull-right
      = link_to 'Редактировать',
                edit_admin_league_match_path(match.season.league.id, match.id)
      |
      = link_to 'Удалить',
                admin_league_match_path(match.season.league.id, match.id),
                method: :delete,
                data: { confirm: 'Вы уверены?' }
.text-center
  = will_paginate previous_label: 'Предыдущая', next_label: 'Следующая'

app/views/admin/matches/list.html.haml
- provide(:title, 'Сезоны по лигам и странам')

%h1 Выберите сезон лиги
- @countries.each do |country|
  .country
    %h2= country.name
    - country.leagues.each do |league|
      .league
        %h3= league.name
        %ul.list-group
          - league.seasons.each do |season|
            %li.list-group-item
              - if path == :admin_league_season_matches_path
                = link_to season.name, send(path, league.id, season.id)
              - else
                = link_to season.name, send(path, league.id)

app/views/admin/matches/new.html.haml
- provide(:title, 'Добавление матча')

.row
  .col-md-6.col-md-offset-3
    %h1.text-center Добавление матча

    = form_for(@match, url: admin_league_matches_path(@league.id)) do |f|
      = render 'shared/error_messages', object: @match

      .form-group
        = f.label :started_on, 'Дата'
        .form-inline
          = f.date_select :play_date, { use_two_digit_numbers: true }, class: 'form-control'

      .form-group
        = f.label :home_id, 'Клуб хозяин'
        = f.collection_select(:home_id, @clubs, :id, :name, {}, class: 'form-control')

      .form-group
        = f.label :away_id, 'Клуб гость'
        = f.collection_select(:away_id, @clubs, :id, :name, {}, class: 'form-control')

      .form-inline
        = f.text_field :home_score, class: 'form-control', placeholder: 'Голы хозяина'
        %span.colon :
        = f.text_field :away_score, class: 'form-control', placeholder: 'Голы гостей'

      .form-inline
        = f.text_field :home_penalty, class: 'form-control', placeholder: 'Пенальти хозяина'
        %span.colon :
        = f.text_field :away_penalty, class: 'form-control', placeholder: 'Пенальти гостей'
        %p.help-block
          Если отсутсвовали послематчевые пенальти поля оставлять пустыми

      .form-group
        = f.label :video, 'Видео', class: 'sr-only'
        = f.text_area :video, class: 'form-control', placeholder: 'Видео'

      .form-group
        = f.label :season_id, 'Сезон'
        = f.collection_select(:season_id, @seasons, :id, :name, {}, { class: 'form-control' })

      = f.submit 'Добавить', class: 'btn btn-lg btn-primary btn-block'

app/views/admin/matches/show.html.haml
- provide(:title, @match.title)

%h1.text-center Матч
%table.table
  %tbody
    %tr
      %th Дата
      %td= l @match.play_date
    %tr
      %th Лига
      %td= @match.season.league.name
    %tr
      %th Сезон
      %td= @match.season.name
    %tr
      %th Клуб хозяин
      %td= @match.home.name
    %tr
      %th Клуб гость
      %td= @match.away.name
    %tr
      %th Счёт
      %td= "#{@match.home_score} : #{@match.away_score}"
    - if @match.home_penalty.present?
      %tr
        %th Послематчевые пенальти
        %td= "#{@match.home_penalty} : #{@match.away_penalty}"
    %tr
      %th Видео
      %td= raw @match.video