config/routes.rb
Rails.application.routes.draw do

  scope module: 'shared' do
    resources :account_activations, only: [:edit]
    resources :password_resets, only: [:new, :create, :edit, :update]
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
    get '/signup', to: 'users#new'
    post '/signup', to: 'users#create'
  end

  namespace :admin do
    root 'pages#index'
    resources :users, except: :new
    resources :countries
    resources :leagues do
      resources :seasons do
        resources :matches, only: :index
      end
      resources :matches
    end
    resources :seasons, only: [:index, :new]
    resources :matches, only: [:index, :new]
    resources :clubs
  end

  scope module: 'site' do
    root 'matches#index'
    get '/search',   to: 'matches#search'
    get '/contacts', to: 'pages#contacts'
    get '/about',    to: 'pages#about'
    get '/:league_slug',              to: 'leagues#matches', as: 'league_matches'
    get '/:league_slug/:season_slug', to: 'seasons#matches', as: 'season_matches',
        season_slug: /\d{4}-\d{4}/
    get '/:league_slug/:season_slug/:club_slug', to: 'clubs#matches',
        as: 'club_matches', season_slug: /\d{4}-\d{4}/
    get '/:league_slug/:match_slug',  to: 'matches#show',  as: 'match'

  end

end

app/views/layouts/admin/_footer.html.haml
%footer#footer.footer
  .container
    .copyright.text-center!= "TheResults &copy; #{Time.zone.now.year}"

app/views/layouts/admin/_header.html.haml
%header#header
  %nav.navbar.navbar-inverse.navbar-fixed-top
    .container
      = link_to 'TheResults.ru', admin_root_path, class: 'logo navbar-brand'
      %ul.nav.navbar-nav.navbar-left
        %li.dropdown
          %a.dropdown-toggle{href: '#', 'data-toggle' => :dropdown,
                             role: :button, 'aria-haspopup' => :true,
                             'aria-expanded' => :false}
            Страна <span class="caret"></span>
          %ul.dropdown-menu
            %li= link_to 'Добавить', new_admin_country_path
            %li= link_to 'Редактировать/Удалить', admin_countries_path
        %li.dropdown
          %a.dropdown-toggle{href: '#', 'data-toggle' => :dropdown,
                             role: :button, 'aria-haspopup' => :true,
                             'aria-expanded' => :false}
            Лига <span class="caret"></span>
          %ul.dropdown-menu
            %li= link_to 'Добавить', new_admin_league_path
            %li= link_to 'Редактировать/Удалить', admin_leagues_path
        %li.dropdown
          %a.dropdown-toggle{href: '#', 'data-toggle' => :dropdown,
                              role: :button, 'aria-haspopup' => :true,
                              'aria-expanded' => :false}
            Клуб <span class="caret"></span>
          %ul.dropdown-menu
            %li= link_to 'Добавить', new_admin_club_path
            %li= link_to 'Редактировать/Удалить', admin_clubs_path
        %li.dropdown
          %a.dropdown-toggle{href: '#', 'data-toggle' => :dropdown,
                              role: :button, 'aria-haspopup' => :true,
                              'aria-expanded' => :false}
            Сезон <span class="caret"></span>
          %ul.dropdown-menu
            %li= link_to 'Добавить', new_admin_season_path
            %li= link_to 'Редактировать/Удалить', admin_seasons_path
        %li.dropdown
          %a.dropdown-toggle{href: '#', 'data-toggle' => :dropdown,
                              role: :button, 'aria-haspopup' => :true,
                              'aria-expanded' => :false}
            Матч <span class="caret"></span>
          %ul.dropdown-menu
            %li= link_to 'Добавить', new_admin_match_path
            %li= link_to 'Редактировать/Удалить', admin_matches_path
      %ul.nav.navbar-nav.navbar-right
        %li.dropdown
          %a.dropdown-toggle{href: '#', 'data-toggle' => :dropdown,
                              role: :button, 'aria-haspopup' => :true,
                              'aria-expanded' => :false}
            Аккаунт <span class="caret"></span>
          %ul.dropdown-menu
            %li= link_to 'Профиль', admin_user_path(@current_user)
            - if @current_user.role == 'admin'
              %li= link_to 'Пользователи', admin_users_path
            %li= link_to 'Выйти', logout_path, method: :delete