config/routes.rb
Rails.application.routes.draw do

  scope module: 'shared' do
    resources :account_activations, only: [:edit]
    resources :password_resets, only: [:new, :create, :edit, :update]
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
    get '/signup', to: 'users#new'
    post '/signup', to: 'users#create'
  end

  namespace :admin do
    root 'pages#index'
    resources :users, except: :new
    resources :countries
    resources :leagues do
      resources :seasons do
        resources :matches, only: :index
      end
      resources :matches
    end
    resources :seasons, only: [:index, :new]
    resources :matches, only: [:index, :new]
    resources :clubs
  end

  scope module: 'site' do
    root 'matches#index'
    get '/search',   to: 'matches#search'
    get '/contacts', to: 'pages#contacts'
    get '/about',    to: 'pages#about'
    get '/:league_slug',              to: 'leagues#matches', as: 'league_matches'
    get '/:league_slug/:season_slug', to: 'seasons#matches', as: 'season_matches',
        season_slug: /\d{4}-\d{4}/
    get '/:league_slug/:season_slug/:club_slug', to: 'clubs#matches',
        as: 'club_matches', season_slug: /\d{4}-\d{4}/
    get '/:league_slug/:match_slug',  to: 'matches#show',  as: 'match'

  end

end

app/models/country.rb
# TODO add case-insensetive index on database level for name attribute
class Country < ActiveRecord::Base
  has_many :leagues
  has_many :clubs

  after_validation {
    retain_specified_errors(%i(name flag))
  }

  validates :name, presence: true,
                   format: { with: /\A[а-яё]+[ а-яё-]*[а-яё]+\z/i,
                             message: 'должно содержать только кириллические
                                       символы, дефисы и пробелы' },
                   uniqueness: { case_sensitive: false }
  validates_each :name do |record, attr, value|
    record.errors.add(attr, 'должно начинаться с большой буквы') if value =~
        /\A[[:lower:]]/
  end
  has_attached_file :flag, styles: lambda { |attachment|
    attachment.instance.is_image? ? { original: 'x150' } : {}
  }

  validates_with AttachmentPresenceValidator,    attributes: :flag
  validates_with AttachmentContentTypeValidator, attributes: :flag,
                                                 content_type: /\Aimage\/.*\Z/
  validates_with AttachmentSizeValidator,        attributes: :flag,
                                                 less_than: 350.kilobytes

  def is_image?
    flag_content_type =~ /\Aimage\/.*\Z/
  end

  private

    def retain_specified_errors(attrs_to_retain)
      errors.each do |attr|
        unless attrs_to_retain.include?(attr)
          errors.delete(attr)
        end
      end
    end
end

app/controllers/admin/countries_controller.rb
class Admin::CountriesController < AdminBaseController
  before_action :set_roles
  before_action :require_authorization, except: [:index, :show]

  def index
    @countries = Country.all.order(name: :asc)
  end

  def new
    @country = Country.new
  end

  def create
    @country = Country.new(country_params)
    if @country.save
      flash[:success] = 'Страна добавлена'
      redirect_to([:admin, @country])
    else
      render 'new'
    end
  end

  def show
    @country = Country.find(params[:id])
  end

  def edit
    @country = Country.find(params[:id])
  end

  def update
    @country = Country.find(params[:id])
    if @country.update(country_params)
      flash[:success] = 'Страна отредактирована'
      redirect_to([:admin, @country])
    else
      render 'edit'
    end
  end

  def destroy
    @country = Country.find(params[:id])
    @country.destroy
    flash[:success] = 'Страна удалена'
    redirect_to request.referrer || admin_root_url
  end

  private

    def set_roles
      @roles = %w(moderator admin)
    end

    # Use strong_parameters for attribute whitelisting
    # Be sure to update your create() and update() controller methods.
    def country_params
      params.require(:country).permit(:name, :flag)
    end
end

app/helpers/admin/countries_helper.rb
module Admin::CountriesHelper
end

app/views/admin/countries/edit.html.haml
- provide(:title, "Редактирование #{@country.name}")

.row
  .col-md-6.col-md-offset-3
    %h1.text-center Редактирование страны

    = form_for([:admin, @country], html: { multipart: true }) do |f|
      .form-group
        = f.label :name, 'Название', class: 'sr-only'
        = f.text_field :name, class: 'form-control', placeholder: 'Название'

      .form-group
        = f.label :flag, 'Флаг'
        = f.file_field :flag

      = f.submit 'Редактировать', class: 'btn btn-lg btn-primary btn-block'

app/views/admin/countries/index.html.haml
- provide(:title, 'Список лиг')

%ul.list-group
  - @countries.each do |country|
    %li.list-group-item
      = link_to country.name, [:admin, country]
      .actions.pull-right
        = link_to 'Редактировать', edit_admin_country_path(country)
        |
        = link_to 'Удалить', [:admin, country], method: :delete,
                  data: { confirm: 'Вы уверены?' }

app/views/admin/countries/new.html.haml
- provide(:title, 'Добавление страны')

.row
  .col-md-6.col-md-offset-3
    %h1.text-center Добавление страны

    = form_for([:admin, @country], html: { multipart: true }) do |f|
      = render 'shared/error_messages', object: @country

      .form-group
        = f.label :name, 'Название', class: 'sr-only'
        = f.text_field :name, class: 'form-control', placeholder: 'Название'

      .form-group
        = f.label :flag, 'Флаг'
        = f.file_field :flag

      = f.submit 'Добавить', class: 'btn btn-lg btn-primary btn-block'

app/views/admin/countries/show.html.haml
- provide(:title, @country.name)

%h1.text-center Страна
%table.table
  %thead
    %tr
      %th Название
      %th Флаг
  %tbody
    %tr
      %td= @country.name
      %td= image_tag(@country.flag.url, class: 'flag')